### ISSUE TITLE
Please avoid violating intellectual property

### ISSUE THREAD

**Issue by cmllr** [flynnham/swlinux.org#1]
I noticed you forked cmllr/distrochooser a few weeks ago and started to renamed into "switch linux". Either the fork is not existing anymore (what I guess) or you turned the fork private (what would be a violation of the license). I'm assuming the fork is simply not existing anymore. Let's leave it at that.

Although Open Source license should not be your personal copy template - I'm fine with that. Kind of grumpy, but I'm fine with that (I have to, that's the disadvantage of OSS). Anybody can create a fork and start renaming it. That's business.

But: I'm upset about the fact, that you used the contents of the distrochooser database for your project. Your questions (/ their structure, except the last one) are ridiculous close to the ones on distrochooser.de. 

The problem is: The database based content does not use a OSS license and is not part of cmllr/distrochooser. Strictly speaking this is a violation of intellectual property.

**Example:** 

|switchlinux.org|distrochooser.de|
|---|---|
|*What do you want to use Linux for?* Daily Use, Privacy, Data rescue, Video Games, Scientific|*Software: Use case:* [...]for daily use, [...]anonymous web browsing., [...]data rescue, [...]supported by game publishers, [...]scientific purposes|

I know that some properties of distributions may lead to similar question structures, but please, some of them are way to close to mine.

Finally, I request you to use your own question <> answer content instead of copy-pasting (and just slighty changing) other's work. I don't want to forbid you to work on projects like this, but please fuel your app with your own ideas. And maybe try to create a _new_ user expierience instead of just realigning elements.

I hope we can resolve this problem without starting a nuclear war 💣! 

Thank you!

Best regards,
Christoph

**Comment by flynnham** [comment]
If you actually look at this project, it's built completely different than your application, as my application does not have any back-end framework, or use any of the code included in your project. There is no money to be made from this (since I do not plan on monetizing it at any time).

If you wish to take legal action on my non-infringing project, I won't stop you. I was directly inspired by your project, and will certainly give credit where due. I apologize for this inconvenience,

Also, those articles (used for descriptions) were sourced directly in my code. I found the original sourced that you used to make those descriptions. If there is any way I can resolve this dispute with you I would wish to do so, as long as it means I don not have to take down this code. I put a lot of work into this project, everything built from scratch using Webpack.

I look forward to hearing from you.

- Flynn Buckingham

**Comment by flynnham** [comment]
https://github.com/flynnham/swlinux.org/blob/master/values/lang/en_us.json

Inside of this file are `src` attributes where I found sources equivalent to the ones in your application. It took many hours, and if it means this much to you I am willing to rewrite each  entry if I can. It will take me many hours, but I actually feel awful knowing that it's affected you and your project this much.

I am very passionate about open source code, and am willing to help in any way that I can.

**Comment by flynnham** [comment]
As for the "Scientific Uses" and such, saying that two or three word sentences fall under the "intellectual property" rule is absolutely absurd. I can certainly look for alternative wordings if that helps.

Actually, I'll do that now. That's one thing off the list. I respect you and your works.

**Comment by flynnham** [comment]
The issue should now be resolved from the latest commits https://github.com/flynnham/swlinux.org/commit/2ae2052669e80287ddbb023f50fdf61fd4d4f135 https://github.com/flynnham/swlinux.org/commit/62df54e764a41e31e014f018a65d2a8ac38c600d. If I missed anything feel free to let me know here - I just tried comparing it with your site to see what seemed similar.

**Comment by flynnham** [comment]
After a whole day of contemplation I feel like I left the wrong impression. @cmllr I have sent an email to your publicly listed email. I would really appreciate if you could give it a read, as it outlines the origins of this application.

**Comment by flynnham** [comment]
Actually...... I keep rereading your response to me.  And something in particular has stood out to me.

> Finally, I request you to use your own question <> answer content instead of copy-pasting (and just slighty changing) other's work. I don't want to forbid you to work on projects like this, but please fuel your app with your own ideas. And maybe try to create a new user expierience instead of just realigning elements.

While I understand your frustration; I am actually extremely offended by this, especially that final accusation. How is the markup even close to the markup of you application??? If you could actually give evidence in regards to this, I would not be taking offense to this at all. Either you have no idea what you are talking about in that sense or you've clearly been misinformed.

I spent over 40 hours tooling and making this app functional to the state it is now. I created everything from the markup, to the code running in the background to the stylings. I fail to see how this application even **remotely** resembles the appearance of your app, with the exception of a couple pairs of wordings.

If you had just said **your just using my wordings and I don't like that, it's infringing on my intellectual property** I would have been fine with that. That makes sense, and yes I did take pointers from your app in that regard. Distrochooser is a fantastic app that gets a a lot of things right. If you would have simply responded to the multiple emails I sent roughly 5 months ago this app would have never existed.

I also love the fact that you mobbed me in regards to having 15 people support your aimless accusation of making a similar UX to yours. It's absolutely pathetic. It's nothing like it, and if you actually spend more than 5 seconds looking at my site you'd know this.

I am retracting my previous apology. What you said is obviously an act of aggression. I ask that you do not open any more issues on this repository. That is such a terrible thing to say, and it's hard to believe I actually looked up to your projects.

**Comment by flynnham** [comment]
[Imgur](http://i.imgur.com/0WfF4hN.png)
Also, I forked your project nearly four months ago in May of this year. You need to get your dates straight.

[response 1](http://i.imgur.com/Fyx1fTK.png)
[response 2](http://i.imgur.com/tHKrFJm.png)

**Comment by flynnham** [comment]
![oh really](https://user-images.githubusercontent.com/6565187/29103594-85077320-7c8e-11e7-8dc0-7d7c85a0af6b.png)
Also, I forked your project nearly four months ago in May of this year. You need to get your dates straight.

![emails1](https://user-images.githubusercontent.com/6565187/29103595-8508179e-7c8e-11e7-9d6d-807020e1cc69.png)
![emails2](https://user-images.githubusercontent.com/6565187/29103596-85082c34-7c8e-11e7-8b9e-aaa2c8244e3f.png)

**Comment by flynnham** [comment]
![thatsfunny](https://user-images.githubusercontent.com/6565187/29103747-7c9b2514-7c8f-11e7-9cf5-4629d5988f81.png)
Huh, that's funny. I forked your project nearly 4 months ago, not "a few weeks ago." I gave up on the fork the same day because I would not be able to do any pull requests unless I could test it on your data. I realized that was fruitless so I just ended up making my own application.

And this has made it clear that I need to continue work on this application, since collaboration won't be possible anymore, at least not from me.

Please get your information sorted out before having the audacity to come to my repository and making claims such as this.

![emails1](https://user-images.githubusercontent.com/6565187/29103883-3a72f616-7c90-11e7-8288-32180dac2a6c.png)
![emails2](https://user-images.githubusercontent.com/6565187/29103884-3a83a664-7c90-11e7-868a-cbd72cc53e0f.png)

**Comment by cmllr** [comment]
I did not remember the correct date. Thats why I wrote "few weeks ago". 

Could you please tell me when you sent me an email? I never got one. Strange. But this could be an issue on my side. I'm currently in drowning in spam, so I maybe accidentally deleted it in a bunch of spam. My fault.

I will now stop to comment this here, but I will respond to your mails now, to make sth. clear what was my intention here. And to de-escalate.

**Comment by ampheul** [comment]
@cmllr It seems a cursory look at his code could have helped sort this out and avoid any vitriol. Kind of unprofessional to bully another developer when you don't even have your facts straight.

**Comment by cmllr** [comment]
@ampheul I may agree on you that my wording was offense. But as I said in my first isse, the point of talk is not about the logical code.
